version: "3.5"

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:7.0.0
    volumes:
      - "${KEYCLOAK_DIR}/demo-realm.json:/tmp/demo-realm.json"
    environment:
      - "KEYCLOAK_USER=${KEYCLOAK_USER}"
      - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
      - "KEYCLOAK_IMPORT=/tmp/demo-realm.json"
    ports:
      - "9999:8080"
